const elementoOndeVoceEsta = document.getElementById('elementoOndeVoceEsta');
const pai = elementoOndeVoceEsta.parentElement;
pai.style.color = 'red';
const primeiroFilhoDoFilho = elementoOndeVoceEsta.firstElementChild;
primeiroFilhoDoFilho.innerText = 'Ainda não é um lobsomem';
const primeiroFilhoDoFilho = pai.firstElementChild;
const primeiroFilho2 = elementoOndeVoceEsta.previousElementSibling;
const textElement = elementoOndeVoceEsta.nextSibling;
const terceiroFilho2 = pai.lastElementChild.previousElementSibling;